## *DataFrames*

In [1]:
import numpy as np
import pandas as pd

In [44]:
data = {
    'Name' : ["John", "Anna", "Peter", "Linda"],
    "Age" : [28, 34, 29, 42],
    "City" : ["New York", "Paris", "Berlin", "London"],
    "Salary" : [65000, 70000, 62000, 85000]
}

#### *Creating a DataFrame*

In [45]:
df = pd.DataFrame(data) #Multiple series

In [46]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [47]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [56]:
df2 = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### *Selection and Indexing of Columns*

In [49]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [50]:
df2[["Name", "Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

#### *Creating a new column*

In [51]:
df2["Designation"] = ["Doctor", "Engineer", "Astraunaut", "Plumber"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000  Astraunaut
3  Linda   42    London   85000     Plumber

#### *Removing a column*

In [52]:
df2.drop("Designation", axis=1) 
# it only shows the snapshot of how data looks after deletion

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [53]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000  Astraunaut
3  Linda   42    London   85000     Plumber

In [54]:
df2.drop(["Designation", "Salary"], axis=1, inplace=True) 
# it actually deletes the columns

In [55]:
df2

    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   42    London

In [57]:
# i restored df here by rerunning the data

In [58]:
df2.drop(1) #inplace will actually delete data

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [60]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [62]:
df2.loc[[0, 2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

#### *Selecting Subsets of Rows and Columns*

In [63]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [64]:
df.loc[[0, 1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [65]:
df.loc[[2, 3]][['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

#### *Conditional Selection*

In [66]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [68]:
# Want to see those people whose age is above 30
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [78]:
# Want to see those people whose age is above 30 and are from Paris
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000