In [2]:
import numpy as np
import pandas as pd

## *Group By*

In [3]:
data = {
    'Category' : ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'], 
    'Store' : ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales' : [100, 200, 150, 250, 120, 180, 200, 300], 
    'Quantity' : [10, 15, 12, 18, 8, 20, 15, 25], 
    'Date' : pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [4]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

## *Group by Category and Calculate the sum of Sales*

In [5]:
df.groupby('Category')

In [6]:
cat = df.groupby('Category')
for i, v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [14]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

## *Group by Store and Calculate the sum of Sales*

In [15]:
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

## *Group by multiple columns*
#### *Group by Category and Store*

In [17]:
 df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [19]:
df.groupby(['Category', 'Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

## *Aggregation*

In [22]:
'''mean, median, mode, min, max, count, std, etc.'''
df['Sales'].mean()

np.float64(187.5)

In [25]:
df['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean       187.500000
min        100.000000
max        300.000000
sum       1500.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64