In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("anime.csv")

In [3]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [4]:
df.columns

Index(['Rank', 'Title', 'Score'], dtype='object')

## *Create a column for no of episodes*

In [5]:
df.loc[1]

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

In [6]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [7]:
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ')':
            check = False
            return data
        if check:
            data += i 
        if i == '(':
            check = True

In [8]:
df['Episodes'] = df['Title'].apply(extract_episodes)

In [9]:
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [10]:
df['Episodes'] = df['Episodes'].str.replace(" eps", "")

In [11]:
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [12]:
df['Episodes'] = df['Episodes'].apply(lambda x: int(x))

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rank      50 non-null     int64
 1   Title     50 non-null     object
 2   Score     50 non-null     float64
 3   Episodes  50 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.7+ KB

## *Make a new column for time stamp*

In [14]:
df['Title'].loc[10]

'Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview'

In [15]:
def extract_timestamp(txt):
    check = False
    timestamp = ""
    k = 0
    for i in txt:
        if k == 19:
            return timestamp
        if check and k < 19:
            timestamp += i
            k += 1
        if i == ')':
            check = True

In [16]:
df['TimeStamp'] = df['Title'].apply(extract_timestamp)

In [17]:
df.head()

,Rank,Title,Score,Episodes,TimeStamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [21]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1 # +1 to include the starting month
    except:
        return None

In [22]:
df['Months'] = df['TimeStamp'].apply(calculate_total_months)

In [23]:
df.head()

,Rank,Title,Score,Episodes,TimeStamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

## *Which anime has the highest score*

In [18]:
(np.max(df['Score']))

9.1

In [26]:
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

## *Give me top 5 highest scoring anime*

In [29]:
df['Score'].value_counts

<bound method IndexOpsMixin.value_counts of 0     9.10
1     9.07
2     9.06
3     9.06
4     9.05
5     9.04
6     9.04
7     9.04
8     9.04
9     9.03
10    9.03
11    9.02
12    8.99
13    8.99
14    8.98
15    8.94
16    8.94
17    8.93
18    8.93
19    8.91
20    8.91
21    8.89
22    8.88
23    8.88
24    8.87
25    8.84
26    8.84
27    8.83
28    8.83
29    8.82
30    8.82
31    8.81
32    8.81
33    8.80
34    8.80
35    8.79
36    8.79
37    8.79
38    8.78
39    8.78
40    8.77
41    8.77
42    8.76
43    8.75
44    8.75
45    8.74
46    8.73
47    8.72
48    8.71
49    8.71
Name: Score, dtype: float64>

In [31]:
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

## *Which anime has the highest episode count*

In [33]:
df[df['Episodes'] == df['Episodes'].max()]['Title']

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
Name: Title, dtype: object

## *anime with top 5 episodes count*

In [43]:
df_sorted_by_episodes_count = df.sort_values(by='Episodes', ascending=False)
df_sorted_by_episodes_count.head()

,Rank,Title,Score,Episodes,TimeStamp,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18

## *which is the longest running anime*

In [44]:
df.head()

,Rank,Title,Score,Episodes,TimeStamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [47]:
df[df['Months'] == df['Months'].max()]

,Rank,Title,Score,Episodes,TimeStamp,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111