In [1]:
import numpy as np
import pandas as pd

In [2]:
# importing csv
data = pd.read_csv('data_cleaning_practice.csv')

In [3]:
data.head()

,ID,Name,Email,Age,City,Salary,Joining_Date,Gender
0,16.0,Isha,isha@example.com,23.0,Mumbai,64000.0,2026-09-09,Female
1,10.0,Sonal,sonal@example.com,29.0,Nashik,54000.0,2026-08-18,Female
2,1.0,Rutik,rutik@example.com,21.0,Pune,85000.0,2026-01-15,Male
3,9.0,Kiran,kiran@example.com,28.0,Nagpur,NaN,11/08/2026,Other
4,18.0,Om,om@example.com,21.0,Pune,62000.0,2026-09-12,Male

In [4]:
data.columns

Index(['ID', 'Name', 'Email', 'Age', 'City', 'Salary', 'Joining_Date',
       'Gender'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            22 non-null     float64
 1   Name          22 non-null     object
 2   Email         21 non-null     object
 3   Age           21 non-null     float64
 4   City          21 non-null     object
 5   Salary        21 non-null     float64
 6   Joining_Date  22 non-null     object
 7   Gender        21 non-null     object
dtypes: float64(3), object(5)
memory usage: 1.6+ KB

In [6]:
data.describe()

              ID         Age        Salary
count  22.000000   21.000000     21.000000
mean   10.272727   29.952381  61666.666667
std     5.708655   28.290416  26357.794546
min     1.000000   -2.000000 -45000.000000
25%     6.000000   23.000000  59000.000000
50%    10.000000   25.000000  65000.000000
75%    14.750000   28.000000  72000.000000
max    20.000000  150.000000  95000.000000

In [7]:
pd.options.display.max_rows

60

In [8]:
pd.options.display.max_rows = 25
pd.options.display.max_rows

25

In [9]:
data

,ID,Name,Email,Age,City,Salary,Joining_Date,Gender
0,16.0,Isha,isha@example.com,23.0,Mumbai,64000.0,2026-09-09,Female
1,10.0,Sonal,sonal@example.com,29.0,Nashik,54000.0,2026-08-18,Female
2,1.0,Rutik,rutik@example.com,21.0,Pune,85000.0,2026-01-15,Male
3,9.0,Kiran,kiran@example.com,28.0,Nagpur,NaN,11/08/2026,Other
4,18.0,Om,om@example.com,21.0,Pune,62000.0,2026-09-12,Male
5,13.0,Arjun,arjun@example.com,150.0,Pune,73000.0,2026-09-03,Male
6,2.0,Amit,amit@example.com,NaN,Mumbai,72000.0,15/02/2026,Male
7,14.0,Tanvi,tanvi@example.com,26.0,Nashik,-45000.0,2026-09-05,Female
8,6.0,Amit,amit@example.com,25.0,Mumbai,72000.0,2026-02-15,Male
9,3.0,Sneha,sneha@example,22.0,pune,65000.0,2026/03/10,Female
10,12.0,Meena,meena@example.com,31.0,Mumbai,62000.0,2026-09-01,Female
11,6.0,Amit,amit@example.com,25.0,Mumbai,72000.0,2026-02-15,Male
12,4.0,Priya,priya@example.com,23.0,Nashik,70000.0,10-04-2026,female
13,5.0,Rahul,NaN,24.0,Mumbai,68000.0,2026-05-20,Male
14,19.0,Aditya,aditya@example.com,25.0,Mumbai,71000.0,invalid_date,Male
15,17.0,Riya,riya@example.com,22.0,pune,67000.0,2026-09-11,F
16,10.0,Sonal,sonal@example.com,29.0,Nashik,54000.0,2026-08-18,Female
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,8.0,Vikram,vikram@example.com,27.0,NaN,95000.0,2026-07-11,Male
19,11.0,Rohit,rohit@example.com,30.0,Pune,58000.0,2026-08-20,M
20,15.0,Sagar,sagar@example.com,24.0,Pune,59000.0,2026-09-07,NaN
21,20.0,Pooja,pooja@example.com,26.0,Nashik,56000.0,2026-09-15,Female
22,7.0,Neha,NEHA@EXAMPLE.COM,-2.0,Pune,61000.0,2026-06-05,F

In [10]:
data.isna()

       ID   Name  Email    Age   City  Salary  Joining_Date  Gender
0   False  False  False  False  False   False         False   False
1   False  False  False  False  False   False         False   False
2   False  False  False  False  False   False         False   False
3   False  False  False  False  False    True         False   False
4   False  False  False  False  False   False         False   False
5   False  False  False  False  False   False         False   False
6   False  False  False   True  False   False         False   False
7   False  False  False  False  False   False         False   False
8   False  False  False  False  False   False         False   False
9   False  False  False  False  False   False         False   False
10  False  False  False  False  False   False         False   False
11  False  False  False  False  False   False         False   False
12  False  False  False  False  False   False         False   False
13  False  False   True  False  False   False         False   False
14  False  False  False  False  False   False         False   False
15  False  False  False  False  False   False         False   False
16  False  False  False  False  False   False         False   False
17   True   True   True   True   True    True          True    True
18  False  False  False  False   True   False         False   False
19  False  False  False  False  False   False         False   False
20  False  False  False  False  False   False         False    True
21  False  False  False  False  False   False         False   False
22  False  False  False  False  False   False         False   False

In [11]:
data.drop(data.index[17], inplace=True)

In [12]:
data

,ID,Name,Email,Age,City,Salary,Joining_Date,Gender
0,16.0,Isha,isha@example.com,23.0,Mumbai,64000.0,2026-09-09,Female
1,10.0,Sonal,sonal@example.com,29.0,Nashik,54000.0,2026-08-18,Female
2,1.0,Rutik,rutik@example.com,21.0,Pune,85000.0,2026-01-15,Male
3,9.0,Kiran,kiran@example.com,28.0,Nagpur,NaN,11/08/2026,Other
4,18.0,Om,om@example.com,21.0,Pune,62000.0,2026-09-12,Male
5,13.0,Arjun,arjun@example.com,150.0,Pune,73000.0,2026-09-03,Male
6,2.0,Amit,amit@example.com,NaN,Mumbai,72000.0,15/02/2026,Male
7,14.0,Tanvi,tanvi@example.com,26.0,Nashik,-45000.0,2026-09-05,Female
8,6.0,Amit,amit@example.com,25.0,Mumbai,72000.0,2026-02-15,Male
9,3.0,Sneha,sneha@example,22.0,pune,65000.0,2026/03/10,Female
10,12.0,Meena,meena@example.com,31.0,Mumbai,62000.0,2026-09-01,Female
11,6.0,Amit,amit@example.com,25.0,Mumbai,72000.0,2026-02-15,Male
12,4.0,Priya,priya@example.com,23.0,Nashik,70000.0,10-04-2026,female
13,5.0,Rahul,NaN,24.0,Mumbai,68000.0,2026-05-20,Male
14,19.0,Aditya,aditya@example.com,25.0,Mumbai,71000.0,invalid_date,Male
15,17.0,Riya,riya@example.com,22.0,pune,67000.0,2026-09-11,F
16,10.0,Sonal,sonal@example.com,29.0,Nashik,54000.0,2026-08-18,Female
18,8.0,Vikram,vikram@example.com,27.0,NaN,95000.0,2026-07-11,Male
19,11.0,Rohit,rohit@example.com,30.0,Pune,58000.0,2026-08-20,M
20,15.0,Sagar,sagar@example.com,24.0,Pune,59000.0,2026-09-07,NaN
21,20.0,Pooja,pooja@example.com,26.0,Nashik,56000.0,2026-09-15,Female
22,7.0,Neha,NEHA@EXAMPLE.COM,-2.0,Pune,61000.0,2026-06-05,F

In [13]:
data['Age'] = data['Age'].fillna(int(data['Age'].mean()))

data['City'] = data['City'].fillna(data['City'].mode()[0])

data['Salary'] = data['Salary'].fillna(int(data['Salary'].mean()))

In [14]:
data.loc[20, 'Gender'] = 'Male'

In [15]:
data.loc[13, 'Email'] = 'rahul@example.com'

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22 entries, 0 to 22
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            22 non-null     float64
 1   Name          22 non-null     object
 2   Email         22 non-null     object
 3   Age           22 non-null     float64
 4   City          22 non-null     object
 5   Salary        22 non-null     float64
 6   Joining_Date  22 non-null     object
 7   Gender        22 non-null     object
dtypes: float64(3), object(5)
memory usage: 2.1+ KB

In [17]:
data.drop(14, inplace=True)

In [18]:
data['Joining_Date'] = pd.to_datetime(data['Joining_Date'], format='mixed')

In [19]:
data['Email'] = data['Email'].str.lower()
data['City'] = data['City'].str.lower()
data['Gender'] = data['Gender'].str.lower()
data['Name'] = data['Name'].str.lower()

In [20]:
data.loc[(data['Age'] < 0) | (data['Age'] > 100), 'Age'] = data['Age'].mean().astype(int)

In [21]:
data.loc[(data['Salary'] < 0), 'Salary'] = data['Salary'].mean().astype(int)

In [22]:
data['City'] = data['City'].str.strip()

In [23]:
for x in data.index:
    if data.loc[x, 'Gender'] == 'female':
        data.loc[x, 'Gender'] = 'f'
    if data.loc[x, 'Gender'] == 'male':
        data.loc[x, 'Gender'] = 'm'

In [24]:
data.loc[9, 'Email'] = 'sneha@example.com'

In [25]:
data['ID'] = data['ID'].astype(int)

In [29]:
data.drop_duplicates(inplace=True)

In [28]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
15    False
16     True
18    False
19    False
20    False
21    False
22    False
dtype: bool

In [30]:
data

,ID,Name,Email,Age,City,Salary,Joining_Date,Gender
0,16,isha,isha@example.com,23.0,mumbai,64000.0,2026-09-09,f
1,10,sonal,sonal@example.com,29.0,nashik,54000.0,2026-08-18,f
2,1,rutik,rutik@example.com,21.0,pune,85000.0,2026-01-15,m
3,9,kiran,kiran@example.com,28.0,nagpur,61666.0,2026-11-08,other
4,18,om,om@example.com,21.0,pune,62000.0,2026-09-12,m
5,13,arjun,arjun@example.com,30.0,pune,73000.0,2026-09-03,m
6,2,amit,amit@example.com,29.0,mumbai,72000.0,2026-02-15,m
7,14,tanvi,tanvi@example.com,26.0,nashik,61222.0,2026-09-05,f
8,6,amit,amit@example.com,25.0,mumbai,72000.0,2026-02-15,m
9,3,sneha,sneha@example.com,22.0,pune,65000.0,2026-03-10,f
10,12,meena,meena@example.com,31.0,mumbai,62000.0,2026-09-01,f
12,4,priya,priya@example.com,23.0,nashik,70000.0,2026-10-04,f
13,5,rahul,rahul@example.com,24.0,mumbai,68000.0,2026-05-20,m
15,17,riya,riya@example.com,22.0,pune,67000.0,2026-09-11,f
18,8,vikram,vikram@example.com,27.0,mumbai,95000.0,2026-07-11,m
19,11,rohit,rohit@example.com,30.0,pune,58000.0,2026-08-20,m
20,15,sagar,sagar@example.com,24.0,pune,59000.0,2026-09-07,m
21,20,pooja,pooja@example.com,26.0,nashik,56000.0,2026-09-15,f
22,7,neha,neha@example.com,30.0,pune,61000.0,2026-06-05,f

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 0 to 22
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            19 non-null     int64
 1   Name          19 non-null     object
 2   Email         19 non-null     object
 3   Age           19 non-null     float64
 4   City          19 non-null     object
 5   Salary        19 non-null     float64
 6   Joining_Date  19 non-null     datetime64[ns]
 7   Gender        19 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 1.3+ KB

In [32]:
print("Missing values:")
print(data.isna().sum())

print("\nDuplicates:")
print(data.duplicated().sum())

print("\nData types:")
print(data.dtypes)

Missing values:
ID              0
Name            0
Email           0
Age             0
City            0
Salary          0
Joining_Date    0
Gender          0
dtype: int64

Duplicates:
0

Data types:
ID                       int64
Name                    object
Email                   object
Age                    float64
City                    object
Salary                 float64
Joining_Date    datetime64[ns]
Gender                  object
dtype: object