In [30]:
import pandas as pd
import warnings

In [36]:
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('messy_ecommerce_data.csv')
data

,transaction_id,customer_name,join_date,purchase_amount,category,status
0,TXN-101,Sarah Connor,2023-01-15,$150.00,Electronics,Completed
1,TXN-102,mike ross,02/20/2023,89.5,clothings,COMPLETED
2,TXN-103,Harvey Specter,2023-03-01,-45.00,Electronics,Pending
3,TXN-104,Rachel Zane,2023-03-05,NaN,Home & Kitchen,cancelled
4,TXN-105,Louis Litt,2023-03-12,210.0,Electronics,Completed
5,TXN-105,Louis Litt,2023-03-12,210.0,Electronics,Completed
6,TXN-106,NaN,2023/04/01,120.75,Clothings,COMPLETED
7,TXN-107,Donna Paulsen,2023-04-10,999999.00,home & kitchen,Completed

In [4]:
data.columns

Index(['transaction_id', 'customer_name', 'join_date', 'purchase_amount',
       'category', 'status'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transaction_id   8 non-null      object
 1   customer_name    7 non-null      object
 2   join_date        8 non-null      object
 3   purchase_amount  7 non-null      object
 4   category         8 non-null      object
 5   status           8 non-null      object
dtypes: object(6)
memory usage: 516.0+ bytes

In [6]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [7]:
data.drop_duplicates(inplace=True)

In [10]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
6    False
7    False
dtype: bool

In [11]:
data

,transaction_id,customer_name,join_date,purchase_amount,category,status
0,TXN-101,Sarah Connor,2023-01-15,$150.00,Electronics,Completed
1,TXN-102,mike ross,02/20/2023,89.5,clothings,COMPLETED
2,TXN-103,Harvey Specter,2023-03-01,-45.00,Electronics,Pending
3,TXN-104,Rachel Zane,2023-03-05,NaN,Home & Kitchen,cancelled
4,TXN-105,Louis Litt,2023-03-12,210.0,Electronics,Completed
6,TXN-106,NaN,2023/04/01,120.75,Clothings,COMPLETED
7,TXN-107,Donna Paulsen,2023-04-10,999999.00,home & kitchen,Completed

In [13]:
data['purchase_amount'][0] = 150

In [17]:
data['purchase_amount'] = data['purchase_amount'].astype(float)

In [24]:
data.drop(7, inplace=True)

In [37]:
data['purchase_amount'].fillna(data['purchase_amount'].mean(), inplace=True)

In [39]:
data['purchase_amount'] = abs(data['purchase_amount'])

In [44]:
data['join_date'] = pd.to_datetime(data['join_date'], format='mixed')

In [47]:
data.dropna(inplace=True)

In [61]:
data['customer_name'] = data['customer_name'].str.title()
data['category'] = data['category'].str.lower()
data['status'] = data['status'].str.upper()

In [65]:
data['category'][1] = 'clothing'

In [69]:
data = data.drop(columns=(1, 'category'))

In [70]:
data

,transaction_id,customer_name,join_date,purchase_amount,category,status
0,TXN-101,Sarah Connor,2023-01-15,150.00,electronics,COMPLETED
1,TXN-102,Mike Ross,2023-02-20,89.50,clothing,COMPLETED
2,TXN-103,Harvey Specter,2023-03-01,45.00,electronics,PENDING
3,TXN-104,Rachel Zane,2023-03-05,105.05,home & kitchen,CANCELLED
4,TXN-105,Louis Litt,2023-03-12,210.00,electronics,COMPLETED